#!/bin/bash
# source script.cfg
echo "the bucket that will be created"
echo $bucketName

bucketName="distributedsort"
inputBucket="climatesort"
columnName=$1
input=$2
output=$3

# uncomment
# aws s3 mb s3://$bucketName

# the file that contains the public DNS addresses of the linux boxes that we just started
FILE=publicDnsFile.txt

# This loop will ssh into the machines represented by each line generated by the starter script
# The ssh command uses stdin, and hence it directly exits the loop
# to avoid that, we attach the output to nothing, so that it can continue the loop for as long as there are
# lines in the file that we are reading from
# IMPORTANT: We will be runnning the java program on each instance, so we dont wait for one program to
# complete and exit
comds="cd ~/Project; java -Xmx4096m -Xms256m -cp ~/Project/DistributedEC2Sorting-0.0.1-SNAPSHOT-jar-with-dependencies.jar server.Server $i $inputBucket $bucketName > log.txt"
comds1="cd ~/Project; java -Xmx4096m -Xms256m -cp ~/Project/DistributedEC2Sorting-0.0.1-SNAPSHOT-jar-with-dependencies.jar server.Server "
comds2="$inputBucket $bucketName > log.txt"
comdsserver="rm -rf ~/Project/sampleSortPartTemp/; rm ~/Project/sampleSortMyParts/*;cd ~/Project; java -Xmx4096m -Xms256m -cp ~/Project/DistributedEC2Sorting-0.0.1-SNAPSHOT-jar-with-dependencies.jar server.Server 0 $inputBucket $bucketName > log.txt"
#comdsclient="cd ~/Project; java -cp DistributedEC2Sorting-0.0.1-SNAPSHOT-jar-with-dependencies.jar server.Server 0 $inputBucket > ~/Project/log.txt &"
i=0
server="not decided"
while read line;do
        echo "$line"
        echo $i
        if [ $i -eq 0 ]; then
        	server=$line
                `ssh -i MyKeyPair.pem ubuntu@$line -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "${comdsserver}"` < /dev/null &
        else
        	echo "slave instance"
                `ssh -i MyKeyPair.pem ubuntu@$line -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "rm -rf ~/Project/sampleSortPartTemp/; rm ~/Project/sampleSortMyParts/*;cd ~/Project; java -Xmx4096m -Xms256m -cp ~/Project/DistributedEC2Sorting-0.0.1-SNAPSHOT-jar-with-dependencies.jar server.Server $i $inputBucket $bucketName > log.txt"` < /dev/null &
        fi
        i=$((i+1))
done < $FILE
echo "master instance was "$server
sleep 10s
java -cp DistributedEC2Sorting-0.0.1-SNAPSHOT-jar-with-dependencies.jar client.Client $inputBucket $bucketName
# since we started the programs simultaneously, we will wait for the two of them to complete after this step
wait
echo "reached the end of sort script"
echo "exiting sort script"
# uncomment if you wish to download the output to your computer
echo "Downloading the output from the s3 bucket to your computer"
echo aws s3 sync s3://$bucketName/DistributedEC2Sort output/
exit